- docs/meeting-notes/2020-08-24.md
> Add meeting minutes for 8/24/2020 WG meeting

- README.md
> Add Josh Bressers to the readme

- README.md
Completes #14 
Signed-off-by: Morten Linderud <morten@linderud.pw>
> README: Added myself to the list

- README.md
> Adding Matthew Dressman to README

- README.md
Add myself to the list of working group members
> Add Reed Loden to README

- docs/meeting-notes/2020-09-14.md
> Add meeting notes for 2020-09-14 WG meeting

- README.md
Signed-off-by: Paulo Flabiano Smorigo <pfsmorigo@canonical.com>
> Add Paulo Flabiano Smorigo (Ubuntu/Canonical) to the README

- src/schema/vulnerability.schema.json
The schema is currently invalid, this fixes it
> Fix the schema

- README.md
Adding as part of application to join WG
> Add Nicole Schwartz to vulnerability disclosure WG

- README.md
> Add Rhys Arkins to the README

- README.md
Clarify the objectives for this WG under the OpenSSF.
Supersedes #52
> Clarify WG objectives

- docs/meeting-notes/2020-10-26.md
> Add meeting notes for 2020-10-26 WG meeting

- README.md
> Update meeting time according to poll results

- docs/meeting-notes/2020-10-05.md
I saw nobody had added the meeting notes from the first meeting this month so took the liberty of preparing the notes we had from google docs. Please do point out if anything is missing.
Fixes #51
Signed-off-by: Morten Linderud <morten@linderud.pw>
> meeting-notes: Added 2020-10-05

- README.md
> Add Art and Josh as members

- docs/meeting-notes/2020-11-16.md
> Add notes for the 2020-11-16 WG meeting

- docs/meeting-notes/2020-11-30.md
> Add meeting notes for 2020-11-30

- docs/meeting-notes/2020-12-14.md
> Add meeting notes for 2020-12-14

- docs/meeting-notes/2021-01-11.md
> Add notes for the 2021-01-11 WG meeting

- docs/personas.md
When this is merged, it should resolve #80.
> Document OSS vulnerability disclosures personas
